### PR TITLE
Remove isScopeActive() cause of deprecation

### PR DESCRIPTION
**Pull request by DZunke**
In Symfony 2.4 the request_stack Service was added. It is the "Best Practice" way to catch the current request

### CODE REVIEW

**Comment by alquerci** [comment]
Hi @DZunke 

Looks good but it should be good to update the Travis config with required versions for Symfony 3.

Remove:
- PHP 5.4
- Symfony 2.1

Add:
- Symfony 3.0

But the locale can also be fetched from the `translator` service.

PS: I18N implementation of this bundle should be fixed and improved but currently I am really busy.

**Comment by DZunke** [comment]
Seems like the builds for symfony 2.7 are failing cause of the acl component in symfony. composer could not complete the dependencies. don't know if it is ok or to set the dependency to symfony 2.8 ? 

Getting the locale from the `translator` would be ok for me but is it nessacary? I wanted to change the old request dependency to the newer request_stack to ensure the same way of getting the locale and not to crash sth. by changing it to the translator. If you prefer i would change it :smile:

**Comment by alquerci** [comment]
I was tried to find the solution but it is very tricky to catch it. https://github.com/alquerci/FMBbCodeBundle/commits/fix-versioning
with the latest travis build https://travis-ci.org/alquerci/FMBbCodeBundle/builds/113981418

@DZunke To be simple you create PR against the branch 3.0 so make it compatible only for Symfony3 and remove old previous version on test.

**Comment by helios-ag** [comment]
Hi @DZunke, so if @alquerci has no objection in this PR, i would merge and tag it, but can you remove tests versus older symfony versions as suggested.

**Comment by DZunke** [comment]
Has removed tests and dependencies to symfony versions older then 3.0, tests are all green now and also the error with the symfony acl dependency has gone. :smile:

**Pull request merged**
